name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        deno-version: [ 1.x ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno test src

